networks:
  web_network:
    driver: overlay

volumes:
  site_conf:

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KC_HOSTNAME: localhost
      KC_DB_PORT: 5432
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: info
    command:
      - "start-dev"
    ports:
      - "${VITE_KC_PORT}:${VITE_KC_PORT}"
